In [1]:
import pandas as pd

In [7]:
data= { 'name' : ["sudh", "krish", "hitesh", "tulesko"],
       'salary' : [100,200,200,400],
       'mail_id' : ['sudh@ineuron.ai', 'krish@ineuron.ai', 'hitesh@ineuron.ai', 'tulesko@ineuron.ai'],
       'addr' : ['blr', 'mum', 'blr', 'ngp']   
}

In [10]:
df = pd.DataFrame(data, index= [4,5,6,7])

In [11]:
df

name  salary             mail_id addr
4     sudh     100     sudh@ineuron.ai  blr
5    krish     200    krish@ineuron.ai  mum
6   hitesh     200   hitesh@ineuron.ai  blr
7  tulesko     400  tulesko@ineuron.ai  ngp

In [13]:
df.loc[5:6] # named index

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  mum
6  hitesh     200  hitesh@ineuron.ai  blr

In [16]:
df.iloc[1:3] # default index

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  mum
6  hitesh     200  hitesh@ineuron.ai  blr

In [17]:
df = pd.DataFrame(data, index= ['jamal',"sapna",'munjal','pranjal'])

In [18]:
df

name  salary             mail_id addr
jamal       sudh     100     sudh@ineuron.ai  blr
sapna      krish     200    krish@ineuron.ai  mum
munjal    hitesh     200   hitesh@ineuron.ai  blr
pranjal  tulesko     400  tulesko@ineuron.ai  ngp

In [19]:
df = pd.DataFrame(data, index= [0,1,2,3])

In [20]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  mum
2   hitesh     200   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  ngp

In [21]:
data1 = {
    'pf_no' : [233242,45334,567567,234],
    'income_tax' : [324,234,25634,45674],
    'mobile_no' : [423234,345,45764,345432],
    'courses' : ['dl','ml','sql','pandas']
}

In [22]:
df1 = pd.DataFrame(data1)

In [23]:
df1

pf_no  income_tax  mobile_no courses
0  233242         324     423234      dl
1   45334         234        345      ml
2  567567       25634      45764     sql
3     234       45674     345432  pandas

In [ ]:
#concatenation

In [26]:
pd.concat([df,df1])

name  salary             mail_id addr     pf_no  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr       NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  mum       NaN         NaN        NaN   
2   hitesh   200.0   hitesh@ineuron.ai  blr       NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  ngp       NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN  233242.0       324.0   423234.0   
1      NaN     NaN                 NaN  NaN   45334.0       234.0      345.0   
2      NaN     NaN                 NaN  NaN  567567.0     25634.0    45764.0   
3      NaN     NaN                 NaN  NaN     234.0     45674.0   345432.0   

  courses  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
0      dl  
1      ml  
2     sql  
3  pandas

In [27]:
pd.concat([df,df1], axis = 1) # horizontal concat axis 1

name  salary             mail_id addr   pf_no  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  blr  233242         324     423234   
1    krish     200    krish@ineuron.ai  mum   45334         234        345   
2   hitesh     200   hitesh@ineuron.ai  blr  567567       25634      45764   
3  tulesko     400  tulesko@ineuron.ai  ngp     234       45674     345432   

  courses  
0      dl  
1      ml  
2     sql  
3  pandas

In [28]:
data2 = {
    '0' : [233242,45334,567567,234],
    '1' : [324,234,25634,45674],
    '2' : [423234,345,45764,345432],
    '3' : ['dl','ml','sql','pandas']
}

data3 = {
    '0' : [233242,45334,567567,234],
    '1' : [324,234,25634,45674],
    '2' : [423234,345,45764,345432],
    '3' : ['dl','ml','sql','pandas']
}

In [29]:
df2 = pd.DataFrame(data2)

In [30]:
df2

0      1       2       3
0  233242    324  423234      dl
1   45334    234     345      ml
2  567567  25634   45764     sql
3     234  45674  345432  pandas

In [31]:
df3 = pd.DataFrame(data3)

In [32]:
df3

0      1       2       3
0  233242    324  423234      dl
1   45334    234     345      ml
2  567567  25634   45764     sql
3     234  45674  345432  pandas

In [34]:
pd.concat([df2,df3])  # vertical concat axis 0

0      1       2       3
0  233242    324  423234      dl
1   45334    234     345      ml
2  567567  25634   45764     sql
3     234  45674  345432  pandas
0  233242    324  423234      dl
1   45334    234     345      ml
2  567567  25634   45764     sql
3     234  45674  345432  pandas

In [ ]:
# merge operation

In [47]:
data4 = {
    'emp_id' : [101,102,103,104],
    'salary' : [3234,234,234,2343],
    'pf' : [221,235,123,3234]
}

data5 = {
    'emp_id' : [101,102,104,105],
    'mob_no' : [321,123,213,213],
    'house_nu' : [213,34,345,646]
}

In [48]:
df4 = pd.DataFrame(data4)

In [49]:
df5 = pd.DataFrame(data5)

In [50]:
df4

emp_id  salary    pf
0     101    3234   221
1     102     234   235
2     103     234   123
3     104    2343  3234

In [51]:
df5

emp_id  mob_no  house_nu
0     101     321       213
1     102     123        34
2     104     213       345
3     105     213       646

In [55]:
pd.merge(df4,df5, how = 'left')

emp_id  salary    pf  mob_no  house_nu
0     101    3234   221   321.0     213.0
1     102     234   235   123.0      34.0
2     103     234   123     NaN       NaN
3     104    2343  3234   213.0     345.0

In [56]:
pd.merge(df4,df5, how = 'right')

emp_id  salary      pf  mob_no  house_nu
0     101  3234.0   221.0     321       213
1     102   234.0   235.0     123        34
2     104  2343.0  3234.0     213       345
3     105     NaN     NaN     213       646

In [57]:
pd.merge(df4,df5,how = 'outer' )

emp_id  salary      pf  mob_no  house_nu
0     101  3234.0   221.0   321.0     213.0
1     102   234.0   235.0   123.0      34.0
2     103   234.0   123.0     NaN       NaN
3     104  2343.0  3234.0   213.0     345.0
4     105     NaN     NaN   213.0     646.0

In [59]:
pd.merge(df4,df5, how = 'right', on = 'emp_id')

emp_id  salary      pf  mob_no  house_nu
0     101  3234.0   221.0     321       213
1     102   234.0   235.0     123        34
2     104  2343.0  3234.0     213       345
3     105     NaN     NaN     213       646

In [60]:
data6 = {
    'emp_id1' : [101,102,103,104],
    'salary' : [3234,234,234,2343],
    'pf' : [221,235,123,3234]
}

data7 = {
    'emp_id2' : [101,102,104,105],
    'mob_no' : [321,123,213,213],
    'house_nu' : [213,34,345,646]
}

In [61]:
df6 = pd.DataFrame(data6)

In [62]:
df7 = pd.DataFrame(data7)

In [67]:
pd.merge(df6,df7, left_on= 'emp_id1', right_on= 'emp_id2')

emp_id1  salary    pf  emp_id2  mob_no  house_nu
0      101    3234   221      101     321       213
1      102     234   235      102     123        34
2      104    2343  3234      104     213       345

In [68]:
pd.merge(df6,df7, left_on= 'emp_id1', right_on= 'emp_id2', how = 'left')

emp_id1  salary    pf  emp_id2  mob_no  house_nu
0      101    3234   221    101.0   321.0     213.0
1      102     234   235    102.0   123.0      34.0
2      103     234   123      NaN     NaN       NaN
3      104    2343  3234    104.0   213.0     345.0

In [74]:
data8 = {
    'emp_id' : [101,102,103,104],
    'salary' : [3234,234,234,2343],
    'pf' : [221,235,123,3234]
}

data9 = {
    'emp_id' : [101,102,104,105],
    'salary' : [3234,234,234,2343],
    'house_nu' : [213,34,345,646]
}

In [75]:
df8 = pd.DataFrame(data8)

In [78]:
df8

emp_id  salary    pf
0     101    3234   221
1     102     234   235
2     103     234   123
3     104    2343  3234

In [76]:
df9 = pd.DataFrame(data9)

In [79]:
df9

emp_id  salary  house_nu
0     101    3234       213
1     102     234        34
2     104     234       345
3     105    2343       646

In [77]:
pd.merge(df8, df9, on = ['emp_id', 'salary'])

emp_id  salary   pf  house_nu
0     101    3234  221       213
1     102     234  235        34

In [94]:
#join works on rows or index where merge works on columns

In [90]:
data10 = {
    'emp_id1' : [101,102,103,104],
    'salary1' : [3234,234,234,2343],
    'pf' : [221,235,123,3234]
}

data11 = {
    'emp_id2' : [101,102,104,105,34],
    'salary2' : [3234,234,234,2343,324],
    'house_nu' : [213,34,345,646,3456]
}

In [91]:
df10 = pd.DataFrame(data10, index= ['a','b','c','d'])

In [92]:
df11 = pd.DataFrame(data11, ['a','b','d','e','f'])

In [93]:
df10.join(df11)

emp_id1  salary1    pf  emp_id2  salary2  house_nu
a      101     3234   221    101.0   3234.0     213.0
b      102      234   235    102.0    234.0      34.0
c      103      234   123      NaN      NaN       NaN
d      104     2343  3234    104.0    234.0     345.0

In [96]:
df_sales = pd.read_csv('sales_data_final.csv')

In [97]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [102]:
#apply a function to data

In [ ]:
def profit_flag(a):
    if a >= 0:
        return 'Positive'
    else:
        return 'Negative'

In [100]:
df_sales['profit_flag'] = df_sales['profit'].apply(profit_flag)

In [101]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year profit_flag  
0          35.46          Medium  2011    Positive  
1           9.72          Medium  2011    Positive  
2           8.17            High  2011    Positive  
3           4.82            High  2011    Negative  
4           4.70          Medium  2011    Positive  

[5 rows x 22 columns]

In [103]:
def len_customer(a) :
    return len(a)

In [106]:
df_sales['len_cust_name'] = df_sales['customer_name'].apply(len_customer)

#also below can be used directly
# df_sales['len_cust_name'] = df_sales['customer_name'].apply(len)

In [105]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  profit_flag len_cust_name  
0          35.46          Medium  2011     Positive            15  
1           9.72          Medium  2011     Positive            11  
2           8.17            High  2011     Positive            13  
3           4.82            High  2011     Negative            12  
4           4.70          Medium  2011     Positive            11  

[5 rows x 23 columns]

In [109]:
def quantity_flag(a) :
    if a < 5:
        return "low"
    elif a >= 5 and a < 9:
        return "medium"
    else:
        return "high"

In [110]:
df_sales['quantity_flag'] = df_sales['quantity'].apply(quantity_flag)

In [114]:
df_sales.tail()

order_id  order_date ship_date       ship_mode     customer_name  \
51285  CA-2014-115427  12/31/2014  1/4/2015  Standard Class        Erica Bern   
51286    MO-2014-2560  12/31/2014  1/5/2015  Standard Class         Liz Preis   
51287  MX-2014-110527  12/31/2014  1/2/2015    Second Class  Charlotte Melton   
51288  MX-2014-114783  12/31/2014  1/6/2015  Standard Class     Tamara Dahlen   
51289  CA-2014-156720  12/31/2014  1/4/2015  Standard Class     Jill Matthias   

         segment             state        country  market   region  ... sales  \
51285  Corporate        California  United States      US     West  ...    14   
51286   Consumer  Souss-Massa-Draƒ        Morocco  Africa   Africa  ...     4   
51287   Consumer           Managua      Nicaragua   LATAM  Central  ...    26   
51288   Consumer         Chihuahua         Mexico   LATAM    North  ...     7   
51289   Consumer          Colorado  United States      US     West  ...     3   

      quantity discount   profit shipping_cost  order_priority  year  \
51285        2      0.2   4.5188          0.89          Medium  2014   
51286        1      0.0   0.4200          0.49          Medium  2014   
51287        3      0.0  12.3600          0.35          Medium  2014   
51288        1      0.0   0.5600          0.20          Medium  2014   
51289        3      0.2  -0.6048          0.17          Medium  2014   

       profit_flag  len_cust_name quantity_flag  
51285     Positive             10           low  
51286     Positive              9           low  
51287     Positive             16           low  
51288     Positive             13           low  
51289     Negative             13           low  

[5 rows x 24 columns]

In [115]:
df_sales['quantity_squared'] = df_sales['quantity'].apply(lambda x : x **2)

In [116]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  profit_flag  \
0      0.0  106.140         35.46         Medium  2011     Positive   
1      0.1   36.036          9.72         Medium  2011     Positive   
2      0.0   29.640          8.17           High  2011     Positive   
3      0.5  -26.055          4.82           High  2011     Negative   
4      0.1   37.770          4.70         Medium  2011     Positive   

   len_cust_name  quantity_flag quantity_squared  
0             15            low                4  
1             11            low                9  
2             13            low               16  
3             12            low                9  
4             11         medium               25  

[5 rows x 25 columns]

In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [3]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [4]:
np.array([[2,3,4],[5,6,7]])

array([[2, 3, 4],
       [5, 6, 7]])

In [6]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [7]:
l = [[1,2,3,4],[2,3,4,5]]

In [8]:
l[0][0]

1

In [12]:
a = np.array([3,4,5,6], ndmin = 3)

In [13]:
a

array([[[3, 4, 5, 6]]])

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
arr.ndim

2

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
import random

In [19]:
np.random.randint(1,10,(4,4))

array([[9, 5, 5, 8],
       [4, 8, 8, 4],
       [4, 4, 7, 1],
       [9, 9, 6, 9]])

In [20]:
np.random.randint(1,10,(4,4,2))

array([[[2, 1],
        [9, 1],
        [5, 4],
        [9, 4]],

       [[1, 7],
        [5, 8],
        [4, 6],
        [5, 2]],

       [[3, 4],
        [3, 7],
        [9, 4],
        [9, 4]],

       [[6, 5],
        [5, 6],
        [9, 8],
        [8, 7]]])